---
- hosts: all
  roles:
  - role: '{{playbook_dir}}'
  tasks:
  - command: /usr/local/bin/gosu --version
    register: gosu_test_output
  - name: gosu --version
    debug:
      msg: '{{ gosu_test_output.stdout }}'
