---
- name: Testing andrewrothstein.gosu
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'gosu --version'
      ansible.builtin.command: /usr/local/bin/gosu --version
      changed_when: false
      register: gosu_test_output
    - name: Output from 'gosu --version'
      ansible.builtin.debug:
        msg: '{{ gosu_test_output.stdout }}'
