---
- name: Downloading {{ gosu_url }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ gosu_url }}'
    checksum: '{{ gosu_checksum }}'
    dest: '{{ gosu_target_bin }}'
    mode: '755'

- name: Linking {{ gosu_target_link }} to {{ gosu_target_bin }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ gosu_target_bin }}'
    dest: '{{ gosu_target_link }}'
    state: link
