---
- name: resolve platform specific vars
  include_vars: '{{item}}'
  with_first_found:
    - files:
        - '{{ansible_distribution}}-{{ansible_distribution_release}}.yml'
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
      skip: true
      paths:
        - '{{role_path}}/vars'

- name: download gosu...
  become: yes
  become_user: root
  get_url:
    url: '{{gosu_url}}'
    checsum: '{{gosu_checksum}}'
    dest: '{{gosu_target_bin}}'
    mode: 0755

- name: link gosu...
  become: yes
  become_user: root
  file:
    src: '{{gosu_target_bin}}'
    dest: '{{gosu_target_link}}'
